[book]
authors = ["Goran Muminovic"]
language = "en"
multilingual = false
src = "src"
title = "PSG Nextcloud Docs"

[output.html]
default-theme = "navy"
no-section-label = true
git-repository-url = "https://github.com/GogoFC/psg/tree/main"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/GogoFC/psg/edit/main/{path}"
site-url = "/html/"

[output.html.fold]
enable = true
site-url = "/html/"
level = 0
